### ISSUE TITLE
Wrapping error causes

### ISSUE THREAD

**Issue by msanft** [MicahParks/keyfunc#103]
Hey there!

It seems that most errors created by this library seem not to wrap the errors that caused them. Is there any reasoning behind that? I think doing so would make debugging at a first glance a lot easier.

For example, consider this:
https://github.com/MicahParks/keyfunc/blob/d272c92f0acae6ff428ec9dd74ecd281d5dd8115/keyfunc.go#L97-L100

If the returned error would wrap the causing `err`, one could easily figure out why this failed, without constructing their own debugging setup or using a dynamic debugger.

Cheers, Moritz.

**Comment by MicahParks** [comment]
The reason is because error behavior was copied from `/v2`, which was based on an older version of Go.

Now that `/v3` has access to [`errors.Join`](https://pkg.go.dev/errors#Join), which was added in Go 1.20, the package should be wrapping errors with this function.

I'll add this behavior and do a release this evening, eastern USA timezone.

Thank you for bringing this to my attention!

**Comment by MicahParks** [comment]
Please see the newest release [`v3.2.3`](https://github.com/MicahParks/keyfunc/releases/tag/v3.2.3) where each error should be wrapped where appropriate.

**Comment by msanft** [comment]
Thank you so much! Unbelievable that you've addressed this so fast! <3
