### ISSUE TITLE
No error when fail to get jwks

### ISSUE THREAD

**Issue by ps-e** [MicahParks/keyfunc#122]
When I use following code:
``` go
func getJWKS() {
	var err error
	jwksURL := "http://localhost:8080/auth/realms/master/protocol/openid-connect/certs"
	jwks, err = keyfunc.NewDefault([]string{jwksURL})
	if err != nil {
		log.Fatalf("Failed to create JWK Set from resource at the given URL.\nError: %s", err)
		panic(err)
	}
}
```
instead of getting an error I just get log entry:

```
2024/03/28 16:09:00 ERROR Failed to refresh HTTP JWK Set from remote HTTP resource. error="failed to perform HTTP request for JWK Set refresh: Get \"http://localhost:8080/auth/realms/master/protocol/openid-connect/certs\": dial tcp [::1]:8080: connect: connection refused" url=http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
```

Is this expected ?

**Comment by MicahParks** [comment]
Yes, this is expected and due to the default behavior.

For use cases where it's more desirable to fail if the first HTTP request to the remote JWK Set resource isn't successful, you'll want to have this option set to false: `NoErrorReturnFirstHTTPReq`.

For advanced configuration, please see the advanced example:
https://github.com/MicahParks/keyfunc/blob/b237e61e207b6ee2338a100e6c6a44de29c4d7b9/examples/advanced/main.go#L83

**Comment by ps-e** [comment]
ok, thanks
