### ISSUE TITLE
Options should use time values, but not pointer

### ISSUE THREAD

**Issue by nejtr0n** [MicahParks/keyfunc#18]
Time package documentation advises to use values, but not pointers.
https://github.com/golang/go/blob/master/src/time/time.go#L85-L87

https://github.com/MicahParks/keyfunc/blob/3dcaab5ea477ffa465ccce6402bd0311873f6c3f/options.go#L42

**Comment by MicahParks** [comment]
Yup. Typically `time.Duration` should be stored as a value, not a pointer.

However, currently in this project they're all stored as pointers. This is because the presence of the `time.Duration` fields are optionally used to configure the program.

If you've come across an instance where the code follows a pointer reference where it's possible it could be `nil`, please draw attention to it.

**Comment by nejtr0n** [comment]
Imho typical usage in such cases is to use time.IsZero() function
```
type Test struc {
   time time.Time
}

data := &Test{}
fmt.Println(data.time.IsZero())
```

**Comment by nejtr0n** [comment]
Imho we could test zero duration
```
type Test struct {
   duration time.Duration
}

data := &Test{}
fmt.Println(data.duration == 0)
```

**Comment by AlexanderYastrebov** [comment]
The obvious (but not mentioned) problem with pointer values is that it prevents use of struct literal to init options like:
```go
jwks, err := keyfunc.Get(url, keyfunc.Options{
    RefreshInterval: 1 * time.Minute,
})
```

**Comment by MicahParks** [comment]
Please see the [`v0.10.0`](https://github.com/MicahParks/keyfunc/releases/tag/v0.10.0) release.

I plan on doing a `v1.0.0` release sometime within the next few weeks. So anyone should feel free to raise issues about things that could be improved before the first major semver.
