### ISSUE TITLE
Validating with Azure ad token

### ISSUE THREAD

**Issue by sdfarrelliii** [MicahParks/keyfunc#41]
I am attempting to validate an Azure ad token with your package. It is able to parse the token but it fails to validate the signature.  I have used several key URLs such as 

https://login.microsoftonline.com/common/discovery/v2.0/keys
https://login.microsoftonline.com/{tenantid}/discovery/v2.0/keys
https://login.microsoftonline.com/{tenantid}/discovery/keys
https://login.microsoftonline.com/common/discovery/keys
https://login.microsoftonline.com/{tenantid}/discovery/v2.0/keys?appid={appid}
https://login.microsoftonline.com/{tenantid}/discovery/keys?appid={appid}

My parsing code is here:
`jwksURL := "https://login.microsoftonline.com/common/discovery/v2.0/keys"

	jwks, err := keyfunc.Get(jwksURL, keyfunc.Options{})
	if err != nil {
		log.Fatalf("Failed to get the JWKS from the given URL.\nError: %s", err)
	}

	// Parse the JWT.
	token, err := jwt.ParseWithClaims(bearerTokenStr, claims, jwks.Keyfunc)

if err != nil || !token.Valid {
		return nil, errors.New("error validating token")
	}
	return claims, nil
`
Is there an issue with parsing Azure tokens, as I have read that the go-oidc project has seem some issues.

I can send you my token if you need it

Thanks

**Comment by MicahParks** [comment]
I would like to see a token, if you're able to provide one that is expired and does not contain any personal information or other sensitive data.

**Comment by sdfarrelliii** [comment]
This one is expired, it doesnt contain much beyond my name and email. We can delete it from the thread later 

eyJ0eXAiOiJKV1QiLCJub25jZSI6InRwR1BEMFlaWGRLVU0wZDd0MmlyYkpVWnpWMVgtSGEwZkdKRFpsdFkteVkiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zZTA5NzEwMS1lZTE1LTRkZmUtYjQ4NC0yOWRlNjg3YzIxYWYvIiwiaWF0IjoxNjU5NzA4NjQ4LCJuYmYiOjE2NTk3MDg2NDgsImV4cCI6MTY1OTcxMzA1MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhUQUFBQSt2VzNCM0NxS1ByUEY3MzV3SmJiQ3A0ckhaMnduOTVjUWtnTVBUalpWQ0E9IiwiYW1yIjpbInB3ZCJdLCJhcHBfZGlzcGxheW5hbWUiOiJDSEhBIiwiYXBwaWQiOiJlYjZmOThiOC1iMjBhLTRmMDAtYTllZS05YjZhNDk4NTlhODUiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkZhcnJlbGwiLCJnaXZlbl9uYW1lIjoiU3RldmUiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNTkuMi4xNy4xNDEiLCJuYW1lIjoiU3RldmUgRmFycmVsbCIsIm9pZCI6IjhmZmNjOWFmLTc5MzYtNGZjOC05MWRlLTNjYzc5NjQ2OTEyOCIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzN0ZGRUFDMDY5OUMxIiwicmgiOiIwLkFUZ0FBWEVKUGhYdV9rMjBoQ25lYUh3aHJ3TUFBQUFBQUFBQXdBQUFBQUFBQUFBNEFGQS4iLCJzY3AiOiJDYWxlbmRhcnMuUmVhZCBDYWxlbmRhcnMuUmVhZC5TaGFyZWQgQ2FsZW5kYXJzLlJlYWRXcml0ZSBDYWxlbmRhcnMuUmVhZFdyaXRlLlNoYXJlZCBHcm91cC5SZWFkLkFsbCBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgVXNlci5SZWFkQmFzaWMuQWxsIGVtYWlsIiwic3ViIjoiU2FJZUZPQ0o1djF3Q0hqb1ZpMlc5YTZxdnBrR3Q0T3N0bkRVY3I4Sm90OCIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6IjNlMDk3MTAxLWVlMTUtNGRmZS1iNDg0LTI5ZGU2ODdjMjFhZiIsInVuaXF1ZV9uYW1lIjoic2RmYXJyZWxsQG9wZW5paWkuY29tIiwidXBuIjoic2RmYXJyZWxsQG9wZW5paWkuY29tIiwidXRpIjoiY1E4MGlHamp3RUM2bXJXR20tVkpBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiOWI4OTVkOTItMmNkMy00NGM3LTlkMDItYTZhYzJkNWVhNWMzIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJEUGpkM24yM09lNkRVNGR5UDNmX0F5RlB5OHFfZVczNWZSRkpKRFdiLTJvIn0sInhtc190Y2R0IjoxNDA2NjgyNzg1fQ.Xn0hYkYkMCzzoEEd9bPvZm0kr3Ms1vkyD5wLqn7-0Mh9AGBfvNmrXi0yrgyiPONt_2pAD46ciLzaVf8e3Rd2Prewsh5X0Mq1XUa-CfoSgvWMczXy0HuDu_P72od6wPS0R4XSIsRQfBPGNrfiBl130Lm82rNXmEz5qPN-ru_zHoVs5SSabfmMlm4igPXilbKNsevmeVZVvu8El9TKApnmZQDFW2eQF9nJwgkbSGULf5MqjpiSu151Z1nLiZUQLPt36Wl_8EkiGsFoSfqAD3sqVp3gAYKL9M6pI_yQPiNnzTt9O_0SL-7dG7WAxf6tbHoW-rh5yTDyxdvbksgyQ7eRAQ

**Comment by MicahParks** [comment]
It seems the original issue text's code wasn't formatted properly, but I get the idea of the code.

Could you provide more information about the error that's being returned and on which line? The error's full text and Go type would be best. An example of a Go type would be `keyfunc.ErrKIDNotFound`. You could find this by using a debugger. The error text could be gathered by printing the error as a string.

**Comment by MicahParks** [comment]
I'm seeing a `crypto/rsa: verification error`, which is concerning to me. But I haven't evaluated the full scope of what that could mean, yet.

**Comment by MicahParks** [comment]
Could you link to where you read this?

> I have read that the go-oidc project has seem some issues.

**Comment by sdfarrelliii** [comment]
Yes my error is  "crypto/rsa: verification error" inside the parser file

I have seen a large ticket on oidc here https://github.com/coreos/go-oidc/issues/344
I think it is related but unsuure.

**Comment by MicahParks** [comment]
Currently, my best guess is that the key with the `kid` (key ID) that signed the JWT you've provided has been rotated since it was created, causing this RSA verification error. I see the provided JWT was created last week. When keys are rotated, I'm not sure if they change their `kid` or not. I would hope they do, but don't know if that is covered by and specification.

If this was also happening last, week, you may have experienced a different error at the time, but recreating that error would require a JWT signed with the newer key, meaning a JWT that was created today would need to be provided.

The issue linked for `coreos/go-oidc` doesn't seem to be related to their JWK Set directly, it seems to be more of a discussion about Microsoft's implementation of OpenID Connect (OIDC).

If you are developing an application that uses OIDC, I would suggest using the `coreos/go-oidc` or other relevant higher-level package as that is a complex protocol.

As far as what you can do today, creating a new JWT now, then trying to parse & validate it would be the next step. That could show us if they key was rotated, but kept the same `kid`.

**Comment by sdfarrelliii** [comment]
I just refreshed and the kid in my new token is 2ZQpJ3UpbjAYXYGaXEJl8lV0TOI

I am getting the token by having the user log in through the front end and then querying MS for an access token. That token is then appended to the header for my API calls. The new token I just got has an expiry of Aug 08 2022 11:42:38 GMT-0230, seems the token is good for about 5 minutes, but it still returns the same error

**Comment by sdfarrelliii** [comment]
I found the issue. It seems I was sending the access token to my API and that was failing, however I changed my front end so it sends the ID token instead and that returns as valid.  
For keys I ended up using this url 
https://login.microsoftonline.com/{tenantid}/discovery/keys?appid={appid}

This can be closed.
Thank you.

**Comment by MicahParks** [comment]
Wonderful. I'm glad you were able to resolve it. Hopefully next time someone has the same question, they'll find this. 🙂

**Comment by benc-uk** [comment]
I found this issue and was hitting the same, the answer is not to use the ID token, you shouldn't use the ID token as a bearer token when calling your API, you should only use the access token.

The root of the problem is not adding a scope to the app registration in Azure AD, and requesting a token using that scope. See the docs here https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis

Without a custom scope, the audience of the access token will NOT be your application ID, instead it will be set to `00000003-0000-0000-c000-000000000000` which is the GUID of the Microsoft Graph API and not your own app
