### ISSUE TITLE
Question: Why is there an ErrMultipleJWKSSize Error

### ISSUE THREAD

**Issue by Robbilie** [MicahParks/keyfunc#87]
I am curious why there is such an error. I built an application that accepts one or multiple jwks urls and I need to build around this due to this error :/

**Comment by MicahParks** [comment]
Thank you for making this issue, @Robbilie.

My initial thought is there is a technical reason I made this limitation. Perhaps I instead made this decision to discourage people from using `MultipleJWKS` because it's less deficient, but the difference shouldn't be noticeable. I'm reading through the code now. If there's no technical reason for this limitation, I may change it from 2 to 1.

**Comment by MicahParks** [comment]
It looks like there is no technical limitation. @Robbilie, the behavior has changed to what you expect in release `v2.0.2`.

**Comment by Robbilie** [comment]
Much appreciated, one less if statement in my code then :P
